language: python
python:
  - "3.6"

script:
  - pytest tests.py

install:
  - pip install -r requirements.txt

before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on:
      branch: Issue_51
    bucket: skitter-s3
    region: us-east-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: skitter-s3
    key: latest.zip
    bundle_type: zip
    application: Skitter
    deployment_group: SkitterGroup
    region: us-east-1
    on:
      branch: Issue_51
