language: python
python:
  - "3.5"

script:
  - javac -version
  - pytest tests.py

install:
  - pip install -r requirements.txt
  - sudo add-apt-repository ppa:webupd8team/java
  - sudo apt update
  - sudo apt install oracle-java8-installer

before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    bucket: skitter-s3
    region: us-east-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: skitter-s3
    key: latest.zip
    bundle_type: zip
    application: Skitter
    deployment_group: SkitterGroup
    region: us-east-1
