version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/skitter
hooks:
  After_Install:
    - location: deploy_scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy_scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: deploy_scripts/validate_server.sh
      timeout: 30
  ApplicationStop:
    - location: deploy_scripts/stop_server.sh
      timeout: 300
      runas: root
