version: 0.0
os: linux
files:
  - source: ./
    destination: /opt/skitter
hooks:
  AfterInstall:
    - location: deploy_scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: deploy_scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: deploy_scripts/validate_server.sh
      timeout: 30
  ApplicationStop:
    - location: deploy_scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
