version: '3'
services:
  skitter-proxy:
    build: proxy/
    depends_on:
      - skitter
    ports:
      - "80:80"
  skitter:
    build: webserver/
  skitter-auth:
    build: auth/
    depends_on:
      - skitter-proxy
