version: '3'
services:
  skitter-proxy:
    build: proxy/
    depends_on:
      - skitter-1
      - skitter-2
    ports:
      - "80:80"
  skitter-1:
    build: webserver/
  skitter-2:
    build: webserver/
  skitter-auth:
    build: auth/
    depends_on:
      - skitter-proxy
