version: '3'
services:

  skitter:
    build: webserver/

  skitter-ca:
    build: ca/

  skitter-auth-db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=skitter_auth_dbpass

  skitter-auth:
    build: auth/
    depends_on:
      - skitter-auth-db

  skitter-skit-db:
    image: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx128m -Xms128m"

  skitter-skit:
    build: skit/
    depends_on:
      - skitter-skit-db

  skitter-proxy:
    build: proxy/
    depends_on:
      - skitter
      - skitter-auth
    ports:
      - "80:80"
      - "443:443"
