version: '3'
services:
  skitter-proxy:
    build: proxy/
    depends_on:
      - skitter
      - skitter-auth
    ports:
      - "80:80"
      - "443:443"
  skitter:
    build: webserver/
  skitter-auth:
    build: auth/
